export const LARGE_SCREEN_BREAKPOINT = 1919;
export const MEDIUM_SCREEN_BREAKPOINT = 1367;
export const SMALL_SCREEN_BREAKPOINT = 1023;
export const MOBILE_SCREEN_BREAKPOINT = 750;
export const XMOBILE_SCREEN_BREAKPOINT = 480;

export const CANVAS_WIDTH_SCALE = 0.7;
